### ISSUE TITLE
CRSP - rename repo

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/channel-router-setup-processor#135]
As a Tazama system operator
**I want** to remove the channel feature
**so that** the system is as simple as possible to maintain and configure for an inexperienced user; and
**so that** the system performs as fast as possible at the lowest possible cost

## Acceptance Criteria
1. Rename the channel-router-setup-processor repository to event-director
2. Update Docker full stack, jenkins, github actions,  
3. Testing: unit, integration, end-to-end, regression 
See #124 

Assumption
1.  Before AKS & EKS updates

**Comment by Justus-at-Tazama** [comment]
The string "channel-router-setup-processor" appears in the code in the following places in GitHub:

https://github.com/search?q=org%3Afrmscoe%20channel-router-setup-processor&type=code

To be addressed in this ticket to ensure that the sources are properly renamed, instead of relying in GitHub redirects:
